### ISSUE TITLE
Request - Docker

### ISSUE THREAD

**Issue by f0b04707** [mjmccans/airthings-mqtt-ha#1]
Hi ! 

Thanks for the great work ! Would it be possible create a docker image with your script ?

Regards,

WM

**Comment by mjmccans** [comment]
Thank you for the comment, and I hope the script is working well for you. I assume it would be possible to make a docker image for the script but I unfortunately would not know how as I do not use docker myself. However, if you were able to create one or put a script together that does it could be included in this repository for the benefit of others. Another option would be to create an Add-On for Home Assistant but that is also something that I would not know how to do. Sorry I cannot be of more assistance.

**Comment by f0b04707** [comment]
Thanks for the reply ! I will have a look at one of those options.
