### ISSUE TITLE
TypeError: type str doesn't define __round__ method

### ISSUE THREAD

**Issue by Vendo232** [mjmccans/airthings-mqtt-ha#2]
Hi

running into this error, any idea what went wrong? Entities are created in HA but values are "unknown"
using the older version Wave

![image](https://user-images.githubusercontent.com/44098230/118412472-69e5a600-b657-11eb-9a71-5ef4ff20e65d.png)

**Comment by mjmccans** [comment]
Vendo232,

It looks like a sensor value is coming in as a string that I was expecting to come in as a float. I have updated the repository to check for string values and not try to round them. Please update to the latest version and let me know if that fixes your issue. Thank you.
